### PR TITLE
Stub for ServiceConfiguration.configurations should expose Mongo.Collection API

### PR DESCRIPTION
**Pull request by gmsecrieru**
Hi @Sanjo 

I think this PR might address what we previously discussed on [velocity-cli](https://github.com/meteor-velocity/velocity-cli/issues/4).

Thanks for your time!

### CODE REVIEW

**Comment by Sanjo** [comment]
Can you try https://github.com/meteor-velocity/meteor-stubs/tree/fix/service-configuration-stub and tell me if it works.

Doing `ServiceConfiguration.configurations = prototypes.Collection;` has the side effect that when you spy on something of ServiceConfiguration.configurations it also spies on all Mongo collections and vise versa because it is the same object. So we should not do that.

**Comment by gmsecrieru** [comment]
I had no idea of the impact on spying, thanks for the feedback! 

The changes proposed on `fix/service-configuration-stub` do work!
screen shot 2015-10-10 at 10 16 51

I have synced this PR with that so feel free to merge it or close it. Thanks again for your time and for the great work!

**Comment by ghost** [comment]
I have released the fix as 1.1.1.

**Comment by gmsecrieru** [comment]
:+1:

**Pull request merged**
